name: jupyterlab-ros
channels:
- conda-forge
- robostack
dependencies:
- python=3.6
- nodejs=12
- jupyterlab
- ipympl
- bqplot
- ipywidgets
- ros-melodic-ros-core
- ros-melodic-rospy
- ros-melodic-rosbridge-suite
- ros-melodic-rosbag
- ros-melodic-rosauth
- ros-melodic-tf2-web-republisher
- ros-melodic-franka-ros
- ros-melodic-interactive-marker-tutorials
- ros-melodic-teb-local-planner
- ros-melodic-turtlebot3
- ros-melodic-turtlebot3-fake
